### ISSUE TITLE
How to prepare the dataset

### ISSUE THREAD

**Issue by ZnS-oscar** [zhen6618/OBBInstanceSegmentation#2]
How to prepare the dataset? It is not mentioned in README. 
For example, which path should I put my dataset? Which yaml is used to define the dataset config?
I like this work, looking forward to detailed information about data preparation.

**Comment by zhen6618** [comment]
You can create a new "datasets" folder under OBB_Detection_Module. The data format can refer to [mmrotate](https://github.com/open-mmlab/mmrotate). Create new "datasets" folders in the OSM and OSM_KD directories under OBB_Prompt_based_Segmentation_Module. The data format can refer to [mmsegmentation](https://github.com/open-mmlab/mmsegmentation), and add OBB labels. Please adjust the specific format according to the code.
